[package]
name = "arcana"
version = "0.1.0-dev"
edition = "2018"
resolver = "2"
authors = ["Kai Ren <tyranron@gmail.com>"]

[features]
codegen = ["arcana-codegen"]
es = ["arcana-codegen/es"]

[dependencies]
arcana-codegen = { path = "./codegen", optional = true }
async-trait = "0.1.50"
ref-cast = "1.0.6"
safety-guard = "0.1.9"
#smart-default = "0.6"
[dependencies.derive_more]
    version = "0.99.9"
    default-features = false
    features = ["as_ref", "deref", "deref_mut", "display", "from", "into"]

[workspace]
members = ["codegen", "codegen/impl"]
