[package]
name = "arcana-codegen"
version = "0.1.0-dev"
edition = "2018"
resolver = "2"
authors = ["Kai Ren <tyranron@gmail.com>"]

[lib]
proc-macro = true

[features]
es = ["arcana-codegen-impl/es"]

[dependencies]
arcana-codegen-impl = { path = "./impl" }
proc-macro-error = "1.0.4"

[dev-dependencies]
arcana = { path = "..", features = ["es"] }
