name: CI

on:
  push:
    branches: ["master"]
    tags: ["arcana-*"]
  pull_request:
    branches: ["master"]

env:
  RUST_BACKTRACE: 1

jobs:

  ##########################
  # Linting and formatting #
  ##########################

  clippy:
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/arcana-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy

      - run: make cargo.lint

  rustfmt:
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/arcana-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - run: make cargo.fmt check=yes




  ###########
  # Testing #
  ###########

  feature:
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/v')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { features: "<none>", crate: "arcana-core" }
          - { features: "codegen", crate: "arcana-core" }
          - { features: "es", crate: "arcana-core" }
          - { features: "es,codegen", crate: "arcana-core" }
          - { features: "<none>", crate: "arcana" }
          - { features: "derive", crate: "arcana" }
          - { features: "es", crate: "arcana" }
          - { features: "es,derive", crate: "arcana" }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: cargo +nightly update -Z minimal-versions

      - run: cargo check -p ${{ matrix.crate }} --no-default-features
                   ${{ matrix.features != '<none>'
                       && format('--features {0}', matrix.features)
                       || '' }}
        env:
          RUSTFLAGS: -D warnings

  test:
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/arcana-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      fail-fast: false
      matrix:
        crate:
          - arcana-core
          - arcana-codegen-impl
          - arcana-codegen-shim
          - arcana-codegen
          - arcana
          - arcana-example-chat
        os:
          - ubuntu
          - macOS
          - windows
        toolchain:
          - nightly
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - run: make test crate=${{ matrix.crate }}

# TODO: MSRV currently has no sense since we sit on nightly Rust.
#       Re-enable once again on stable Rust.
#  msrv:
#    name: MSRV
#    if: ${{ github.ref == 'refs/heads/master'
#            || startsWith(github.ref, 'refs/tags/v')
#            || !contains(github.event.head_commit.message, '[skip ci]') }}
#    strategy:
#      fail-fast: false
#      matrix:
#        msrv: ["1.57.0"]
#        os:
#          - ubuntu
#          - macOS
#          - windows
#    runs-on: ${{ matrix.os }}-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: nightly
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: ${{ matrix.msrv }}
#          override: true
#
#      - run: cargo +nightly update -Z minimal-versions
#
#      - run: make test




  #################
  # Documentation #
  #################

  rustdoc:
    if: ${{ github.ref == 'refs/heads/master'
            || startsWith(github.ref, 'refs/tags/arcana-')
            || !contains(github.event.head_commit.message, '[skip ci]') }}
    strategy:
      matrix:
        crate:
          - arcana-core
          - arcana-codegen-impl
          - arcana-codegen-shim
          - arcana-codegen
          - arcana
          - arcana-example-chat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: make cargo.doc crate=${{ matrix.crate }} private=yes open=no
